service: webdemo1
runtime: python37

env_variables:
  RUN_ENV: 'production'

handlers:
- url: /(.*\.(gif|png|jpg|js|json|html|ico|css|map))$
  static_files: build/\1
  upload: build/(.*)
  secure: always

inbound_services:
- warmup